FROM ubuntu:22.04


# 安装基础工具
RUN apt update && apt install -y \
    build-essential \
    gdb \
    cmake \
    vim \
    git \
    make \
    sudo \
    clang \
    clang-format

# 创建开发用户和目录
RUN useradd -m -s /bin/bash developer && \
    echo "developer:123" | chpasswd && \
    echo "developer ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/developer && chmod 440 /etc/sudoers.d/developer

RUN mkdir -p /home/developer/dev && \
    chown developer:developer /home/developer/dev

# 复制启动脚本
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# 设置工作目录和用户
WORKDIR /home/developer/dev
USER developer

# 设置容器入口点为bash（常驻）
ENTRYPOINT ["/entrypoint.sh"]